using TrainingHub.Shared;
using TrainingHub.Shared.Common;
using TrainingHub.Shared.Common.Errors;
using TrainingHub.Shared.Common.Results;
using TrainingHub.Shared.CQS;
using TrainingHub.Shared.Domain.Aggregates.TrainerAggregate;
using TrainingHub.Shared.Application.Factories;
using TrainingHub.Shared.Domain.Aggregates.TrainingAggregate;

namespace TrainingHub.DDDWithCqrs.Application.Features.Trainings.Create;

/// <summary>
/// Asks that a training be created.
/// </summary>
public sealed class CreateTrainingCommand : ICommand<Result>
{
    /// <summary>
    /// The training's identifier. Generated by the command when the caller does not supply one,
    /// so a retried request creates one training rather than two.
    /// </summary>
    public Guid TrainingId { get; init; } = Guid.NewGuid();

    /// <summary>
    /// The training's title, as the caller sent it. Bounds are enforced by the value object,
    /// not here.
    /// </summary>
    public string Title { get; init; } = null!;

    /// <summary>
    /// The topic names to file the training under. Unknown names are a validation error, not
    /// an exception — topics are a closed set the domain owns.
    /// </summary>
    public List<string> Topics { get; init; } = [];

    /// <summary>
    /// The training's description, as the caller sent it.
    /// </summary>
    public string Description { get; init; } = null!;

    /// <summary>
    /// What a participant needs beforehand, as the caller sent it.
    /// </summary>
    public string Prerequisites { get; init; } = null!;

    /// <summary>
    /// What a participant leaves with, as the caller sent it.
    /// </summary>
    public string AcquiredSkills { get; init; } = null!;
}

/// <summary>
/// Runs <see cref="CreateTrainingCommand"/>.
/// </summary>
public sealed class CreateTrainingCommandHandler(
    ITrainingRepository trainingRepository,
    ITrainerRepository trainerRepository,
    IUniquenessTitleChecker titleChecker,
    ITrainingCounter trainingCounter,
    ITrainerStanding trainerStanding,
    ITrainerVerification trainerVerification,
    ICurrentUserService currentUserService,
    IUnitOfWork unitOfWork)
    : ICommandHandler<CreateTrainingCommand, Result>
{
    /// <summary>
    /// Runs the command.
    /// </summary>
    public async ValueTask<Result> Handle(
        CreateTrainingCommand request,
        CancellationToken cancellationToken)
    {
        var trainerId = TrainerId.Create(currentUserService.TrainerId);

        if (!await trainerRepository.ExistsAsync(trainerId, cancellationToken))
        {
            return Result.Failure(ErrorCodes.NotFound,
                $"Trainer with id `{trainerId.Value}` not found.");
        }

        var detailsResult = TrainingDetailsFactory.Create(
            request.Title, request.Description, request.Prerequisites, request.AcquiredSkills, request.Topics);

        var trainingCreationResult = await detailsResult.MatchAsync(
            async details => await Training.CreateAsync(
                TrainingId.Create(request.TrainingId),
                trainerId,
                details.Title,
                details.Description,
                details.Prerequisites,
                details.AcquiredSkills,
                details.Topics,
                titleChecker,
                trainingCounter,
                trainerStanding,
                trainerVerification,
                cancellationToken),
            Result<Training>.FailureAsync);

        return await trainingCreationResult.MatchAsync<Result>(async (training) =>
        {
            trainingRepository.Add(training);
            try
            {
                await unitOfWork.SaveChangesAsync(cancellationToken);
            }
            catch (UniqueConstraintViolationException)
            {
                // A concurrent request slipped past the uniqueness pre-check;
                // the unique index is the authoritative guard, so a lost race
                // is the same business failure as a detected duplicate.
                return Result.Failure(TrainingErrorCodes.DuplicateTitle,
                    "A training with the same title already exists for this trainer.");
            }
            return Result.Success();
        }, Result.FailureAsync);
    }
}
