using BLRefactoring.Shared.Common;
using FluentAssertions;
using Xunit;

namespace BLRefactoring.Shared.Domain.Tests.Common;

public class EntityTests
{
    public class TestEntityId : EntityId<TestEntityId> { }

    public class TestEntity : Entity<TestEntityId> { }

    [Fact]
    public void NewEntity_HasAutoGeneratedId()
    {
        var entity = new TestEntity();

        entity.Id.Should().NotBeNull();
        entity.Id.Value.Should().NotBe(Guid.Empty);
    }

    [Fact]
    public void NewEntity_IsTransient()
    {
        var entity = new TestEntity();

        entity.IsTransient().Should().BeTrue();
    }

    [Fact]
    public void Equals_SameId_ReturnsTrue()
    {
        var id = TestEntityId.Generate();
        var entity1 = new TestEntity { Id = id };
        var entity2 = new TestEntity { Id = id };

        entity1.Equals(entity2).Should().BeTrue();
    }

    [Fact]
    public void Equals_DifferentId_ReturnsFalse()
    {
        var entity1 = new TestEntity();
        var entity2 = new TestEntity();

        entity1.Equals(entity2).Should().BeFalse();
    }

    [Fact]
    public void Equals_Null_ReturnsFalse()
    {
        var entity = new TestEntity();

        entity.Equals(null).Should().BeFalse();
    }

    [Fact]
    public void Equals_DifferentType_ReturnsFalse()
    {
        var entity = new TestEntity();
        object other = "not an entity";

        entity.Equals(other).Should().BeFalse();
    }

    [Fact]
    public void GetHashCode_TransientEntity_UsesReferenceHashCode()
    {
        var id = TestEntityId.Generate();
        var entity1 = new TestEntity { Id = id };
        var entity2 = new TestEntity { Id = id };

        // Both are transient, so GetHashCode uses base.GetHashCode() (reference-based)
        // Two different instances should have different hash codes
        entity1.GetHashCode().Should().NotBe(entity2.GetHashCode());
    }

    [Fact]
    public void OperatorEquals_SameId_ReturnsTrue()
    {
        var entity = new TestEntity();
        var sameRef = entity;

        (entity == sameRef).Should().BeTrue();
    }

    [Fact]
    public void OperatorEquals_BothNull_ReturnsTrue()
    {
        TestEntity? a = null;
        TestEntity? b = null;

        (a == b).Should().BeTrue();
    }

    [Fact]
    public void OperatorEquals_OneNull_ReturnsFalse()
    {
        var entity = new TestEntity();
        TestEntity? nullEntity = null;

        (entity == nullEntity).Should().BeFalse();
    }

    [Fact]
    public void OperatorNotEquals_DifferentId_ReturnsTrue()
    {
        var entity1 = new TestEntity();
        var entity2 = new TestEntity();

        (entity1 != entity2).Should().BeTrue();
    }
}
