using System.Linq.Expressions;
using System.Reflection;

namespace BLRefactoring.Shared.Common;

/// <summary>
/// Represents the identifier of an <see cref="Entity"/>, backed by a <see cref="Guid"/>.
/// An <see cref="EntityId{TEntityId}"/> is a value object, even though it does not inherit from
/// <see cref="ValueObject"/>.
/// </summary>
/// <remarks>
/// <para>
/// <see cref="Create"/> and <see cref="Generate"/> are the construction paths: they validate the
/// value and instantiate the derived type through its non-public constructor, via a factory
/// compiled once per identifier type. Derived id types declare a private constructor taking a
/// <see cref="Guid"/> and chaining the base constructor, which makes bare instantiation
/// (<c>new TrainerId()</c>) a compile error and an empty identifier unrepresentable.
/// </para>
/// <para>
/// Every identifier in this solution is a <see cref="Guid"/> and is meant to stay one, so the
/// underlying type is fixed here rather than left as a second type parameter. The class used to
/// carry one, together with the <c>struct, IComparable&lt;T&gt;, IEquatable&lt;T&gt;</c>
/// constraints it needed and a second class whose only purpose was to pin it to
/// <see cref="Guid"/>. Nothing ever instantiated it with anything else.
/// </para>
/// </remarks>
/// <typeparam name="TEntityId">The derived type that inherits from <see cref="EntityId{TEntityId}"/>.</typeparam>
public abstract class EntityId<TEntityId> :
    IEquatable<EntityId<TEntityId>>,
    IComparable,
    IComparable<EntityId<TEntityId>>
    where TEntityId : EntityId<TEntityId>
{
    private static readonly Func<Guid, TEntityId> Factory = BuildFactory();

    /// <summary>
    /// Gets the underlying value of the identifier.
    /// </summary>
    public Guid Value { get; }

    /// <summary>
    /// Initializes the identifier with a non-empty value.
    /// </summary>
    /// <param name="value">The value of the identifier.</param>
    /// <exception cref="ArgumentException">
    /// Thrown when <paramref name="value"/> is <see cref="Guid.Empty"/>.
    /// </exception>
    protected EntityId(Guid value)
    {
        if (value == Guid.Empty)
        {
            throw new ArgumentException(
                $"A {typeof(TEntityId).Name} cannot be empty.", nameof(value));
        }

        Value = value;
    }

    /// <summary>
    /// Creates a new instance of the <typeparamref name="TEntityId"/> class
    /// with the specified <paramref name="value"/>.
    /// </summary>
    /// <param name="value">The value for the new instance. Must not be <see cref="Guid.Empty"/>.</param>
    /// <returns>A new <typeparamref name="TEntityId"/> holding <paramref name="value"/>.</returns>
    /// <exception cref="ArgumentException">
    /// Thrown when <paramref name="value"/> is <see cref="Guid.Empty"/>.
    /// </exception>
    public static TEntityId Create(Guid value) => Factory(value);

    /// <summary>
    /// Generates a new <typeparamref name="TEntityId"/> with a fresh <see cref="Guid"/>.
    /// </summary>
    /// <remarks>
    /// Identifiers are generated by the caller before the write, so the primary key is known
    /// without a database round-trip.
    /// </remarks>
    public static TEntityId Generate() => Create(Guid.NewGuid());

    /// <summary>
    /// Converts a <see cref="Guid"/> into an identifier, with the same validation as
    /// <see cref="Create"/>.
    /// </summary>
    /// <remarks>
    /// C# requires a conversion operator to be declared in its source or target type, so an
    /// operator living on this generic base can only produce the base type. A cast such as
    /// <c>(TrainerId)guid</c> therefore combines this conversion with a reference downcast —
    /// safe, since <see cref="Create"/> builds the derived type, and invisible at the call site.
    /// Declaring it here rather than on each identifier keeps every present and future id type
    /// convertible without three copies to remember.
    /// </remarks>
    public static explicit operator EntityId<TEntityId>(Guid value) => Create(value);

    private static Func<Guid, TEntityId> BuildFactory()
    {
        var constructor = typeof(TEntityId).GetConstructor(
            BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic,
            binder: null,
            [typeof(Guid)],
            modifiers: null);

        if (constructor is null)
        {
            throw new InvalidOperationException(
                $"{typeof(TEntityId).Name} must declare a constructor taking a single " +
                $"{nameof(Guid)} and chaining the base constructor.");
        }

        var value = Expression.Parameter(typeof(Guid), "value");
        return Expression
            .Lambda<Func<Guid, TEntityId>>(Expression.New(constructor, value), value)
            .Compile();
    }

    public bool Equals(EntityId<TEntityId>? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return Value.Equals(other.Value);
    }

    public override bool Equals(object? obj)
    {
        if (ReferenceEquals(null, obj))
        {
            return false;
        }

        if (ReferenceEquals(this, obj))
        {
            return true;
        }

        if (this.GetType() != obj.GetType())
        {
            return false;
        }

        return Equals((EntityId<TEntityId>)obj);
    }

    public override int GetHashCode()
    {
        return Value.GetHashCode();
    }

    public int CompareTo(object? obj)
    {
        if (obj is TEntityId entityId)
        {
            return CompareTo(entityId);
        }

        throw new ArgumentException($"Object must be of type {typeof(TEntityId).Name}", nameof(obj));
    }

    public int CompareTo(EntityId<TEntityId>? other)
    {
        if (other is null)
        {
            return 1;
        }

        if (ReferenceEquals(this, other))
        {
            return 0;
        }

        return Value.CompareTo(other.Value);
    }

    public static bool operator ==(EntityId<TEntityId>? left, EntityId<TEntityId>? right)
        => Equals(left, right);

    public static bool operator !=(EntityId<TEntityId>? left, EntityId<TEntityId>? right)
        => !Equals(left, right);
}
