<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\TrainingHub.Shared.Application\TrainingHub.Shared.Application.csproj" />
    <ProjectReference Include="..\Domain\TrainingHub.DDD.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
